title: Doctoral Thesis Blog of Kumar Manas
author: Kumar Manas
email: manasmishra888@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Blog created to keep track of doctoral thesis research work and knowledge earned during the phase. Hope that it will keep me sane while writing final report.

# social links
twitter_username: kumarmanas27 # DO NOT include the @ character, or else the build will fail!
github_username:  kumarmanas # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal